#!/usr/bin/env bash

JAVA="$(/usr/libexec/java_home)/bin/java"
JAVA_OPTS="-Xms2g -Xmx2g -XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=40"
APP_DIR="/home/dueunoapp"
APP_NAME="dueunoapp"
APP_VERSION="1.0"

cd "${APP_DIR}"
exec $JAVA ${JAVA_OPTS} -jar ${APP_NAME}-${APP_VERSION}.jar