dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.sqlite.JDBC
  dialect: org.hibernate.dialect.SQLiteDialect

  url: jdbc:sqlite:C:\\mydatabase.db
  username:
  password:

  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: "SELECT 1"
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: "ConnectionState"
    defaultTransactionIsolation: TRANSACTION_READ_UNCOMMITTED


environments:
  development:
    dataSource:
      dbCreate: create-drop

  test:
    dataSource:
      dbCreate: update

  production:
    dataSource:
      dbCreate: update


