# See: https://github.com/grails/grails-core/issues/12874
info.app.name: dueunoapp

# CREATE DEV CERTIFICATE
#
# NOTE: When asked for password just type "password"
#
# cd ${project-dir}/src/main/resources/certificates
# openssl req -x509 -newkey rsa:4096 -keyout dev-key.pem -out dev-cert.pem -days 3650 -subj '/CN=localhost'
# openssl pkcs12 -export -in dev-cert.pem -inkey dev-key.pem -out dev-keystore.p12 -name tomcat -caname root
#
# IMPORTANT: You must give "always trust" permissions to the certificate "certificates/dev-cert.pem" in your
# operating system specific Keychain tool
#
environments:
  development:
    server:
#      port: 8443
      port-http: 8080
#      servlet:
#        context-path: /
#        ssl:
#          enabled: true
#          key-store-type: PKCS12
#          key-store: classpath:certificates/dev-keystore.p12
#          key-store-password: password
#          key-alias: tomcat

# CREATE PRODUCTION CERTIFICATE
# See: https://certbot.eff.org/instructions
#
#  production:
#    server:
#      port: 443
#      port-http: 80
#      servlet:
#        context-path: /
#        session:
#          persistent: true
#          store-dir: dueunoapp
#      ssl:
#        enabled: true
#        key-store-type: PKCS12
#        key-store: /etc/letsencrypt/live/my.domain.com/keystore.p12
#        key-store-password: KeyStorePassword
#        key-alias: grails

server:
  tomcat:
    basedir: dueunoapp/tomcat
  servlet:
    session:
      persistent: true
      store-dir: dueunoapp
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

---
grails:
  profile: web
  codegen:
    defaultPackage: dueuno
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "log"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - '*.gsp'
        - '**/*.gsp'
        - '*.gson'
        - '**/*.gson'
        - 'logback.groovy'
        - '*.properties'
management:
  endpoints:
    enabled-by-default: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
management:
  endpoints:
    jmx:
      unique-names: true

---
spring:
  h2:
    console:
      enabled: true

grails:
  controllers:
    upload:
      maxFileSize: 20000000
      maxRequestSize: 20000000

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  url: jdbc:h2:file:./dueunoapp/dueunoapp;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

environments:
  development:
    grails.logging.jul.usebridge: true
    grails.plugin.springsecurity.debug.useFilter: true
    dataSource:
      dbCreate: update

  test:
    dataSource:
      dbCreate: update

  production:
    dataSource:
      dbCreate: update